name: shunzhuanganliang
on:
  workflow_dispatch:

  schedule:
    - cron: '56 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shunzhuanganliang
        env:
          s5687: ${{ secrets.s5687 }}
        run: |
          printf '%s' "$s5687" | jq -r .hkr43 | /bin/bash
          echo $vxjf111 | jq -r .dhow1 | /bin/bash
          printf '%s' "$bb6" | jq -r .ue0467 | /bin/bash
          echo $oqo7 | jq -r .mcw28 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kaq1Fy4G
          path: "*.zip"
          retention-days: 1
